### ISSUE TITLE
Typegoose

### ISSUE THREAD

**Issue by arrrrny** [tsh96/nest-mongoose-crud#1]
Thanks for your package contribution. I would use it immediately if it was using typegoose deceorators. IS there any reason why you did not choose typegoose and choose mongoose decorators?

**Comment by tsh96** [comment]
Thank you for your valued suggestion. The reasons why I choose `@nestjs/mongoose` instead of `typegoose` are:
1. They look similar.
2. `@nestjs/mongoose` is officially supported by Nest.js

After some readings, I found that `typegoose` provides more features and can be a better choice. To avoid any breaking changes in this package, I plan to create a new package maybe named `@tsh96/nest-typegoose-crud` soon.

**Comment by arrrrny** [comment]
That would be awesome! We have been using typegoose on production for a while and it is such a breeze.
